In [2]:
# Import plotly offline
import plotly
plotly.offline.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import numpy as np
import pandas as pd

# Import pandas
import pandas as pd

In [3]:
# Import machine learning libraries
# Import everything we need.
import csv
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [81]:
# Import data through github link
# https://raw.githubusercontent.com/bendbir/bird_bones/main/bird.csv

url = 'https://raw.githubusercontent.com/bendbir/bird_bones/main/bird.csv'
birds_data = pd.read_csv(url, low_memory=False)
# Dataset is now stored in a Pandas Dataframe

Dataset obtained from Kaggle: https://www.kaggle.com/datasets/zhangjuefei/birds-bones-and-living-habits

In [54]:
print (birds_data.head())

   id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
0   0  80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
1   1  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
2   2  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
3   3  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
4   4  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW


In [55]:
# Print description ('.describe()') of data
birds_data.describe()

id        huml        humw       ulnal       ulnaw        feml  \
count  420.000000  419.000000  419.000000  417.000000  418.000000  418.000000   
mean   209.500000   64.650501    4.370573   69.115372    3.597249   36.872416   
std    121.387808   53.834549    2.854617   58.784775    2.186747   19.979082   
min      0.000000    9.850000    1.140000   14.090000    1.000000   11.830000   
25%    104.750000   25.170000    2.190000   28.050000    1.870000   21.297500   
50%    209.500000   44.180000    3.500000   43.710000    2.945000   31.130000   
75%    314.250000   90.310000    5.810000   97.520000    4.770000   47.120000   
max    419.000000  420.000000   17.840000  422.000000   12.000000  117.070000   

             femw        tibl        tibw        tarl        tarw  
count  419.000000  418.000000  419.000000  419.000000  419.000000  
mean     3.220883   64.662823    3.182339   39.229976    2.930024  
std      2.023581   37.838145    2.080827   23.184313    2.185673  
min      0.930000    5.500000    0.870000    7.770000    0.660000  
25%      1.715000   36.417500    1.565000   23.035000    1.425000  
50%      2.520000   52.120000    2.490000   31.740000    2.230000  
75%      4.135000   82.870000    4.255000   50.250000    3.500000  
max     11.640000  240.000000   11.030000  175.000000   14.090000

In [82]:
data_types = birds_data.dtypes
print("data types:")
print(data_types)

data types:
id         int64
huml     float64
humw     float64
ulnal    float64
ulnaw    float64
feml     float64
femw     float64
tibl     float64
tibw     float64
tarl     float64
tarw     float64
type      object
dtype: object


In [83]:
# first, drop type and id.  Type needs to be dropped since object won't let us use np.isnan()
birds_data_test = birds_data.drop(['id', 'type'], axis = 1)

# Test for NaN
np.where(np.isnan(birds_data_test))

(array([160, 160, 204, 204, 207, 207, 342, 342, 342, 342, 378, 378, 378,
        396, 404]), array([4, 5, 2, 3, 8, 9, 0, 1, 2, 3, 2, 6, 7, 6, 4]))

In [85]:
# If interested, look at row to confirm NaN
# print(DATAFRAME.iloc[ROW])

# Drop NaNs from original dataframe
birds_data2 = birds_data.dropna()

# Test again for NaN, confirm there aren't any
birds_data_test = birds_data2.drop(['id', 'type'], axis = 1)
np.where(np.isnan(birds_data_test))

(array([], dtype=int64), array([], dtype=int64))

In [86]:
# Define feature and target dataframes
# Can we predict bird based on all metrics?

# birdTypeInput is what we input to predict bird type.  Drop id and type since we don't need those.
birdTypeInput = birds_data2.drop(['type'], axis = 1)

# Define target label, in this case 'id'
birdTargetLabel = birds_data2[['type']].copy()

In [87]:
# Use train_test_split, create input_train, input_test, label_train, label_test
input_train, input_test, label_train, label_test = train_test_split(birdTypeInput, birdTargetLabel, stratify = birdTargetLabel)

In [88]:
# Test that the keys match for training dataframes
print (input_train.head())
print (label_train.head())

      id    huml  humw   ulnal  ulnaw   feml  femw    tibl  tibw   tarl  tarw
226  226   83.02  5.95   96.97   4.38  51.87  4.21   66.60  4.06  36.60  5.63
306  306   15.97  1.47   19.91   1.32  15.11  1.24   25.99  1.14  18.36  1.40
238  238  117.43  7.13  136.26   5.51  75.54  5.85  115.30  5.45  59.45  8.25
151  151   82.30  4.88   95.09   4.34  37.39  3.02   75.34  3.19  50.06  2.38
176  176   33.20  2.11   34.31   2.25  20.36  1.57   37.95  1.42  23.67  1.26
    type
226    R
306   SO
238    R
151    W
176    W


In [89]:
# Test that shapes are correct
# Trains and tests should match number of rows
print(input_train.shape)
print(input_test.shape)
print(label_train.shape)
print(label_test.shape)

(309, 11)
(104, 11)
(309, 1)
(104, 1)


In [90]:
# make your model! 
gnb = GaussianNB()
gnb.fit(input_train, label_train)
bird_bone_pred = gnb.predict(input_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



In [91]:
# How well did our model do?
# find the accuracy score.
print("Gaussian Naive Bayes accuracy:", round((accuracy_score(label_test, bird_bone_pred)*100),2))

Gaussian Naive Bayes accuracy: 76.92


In [92]:
# Let's take a look at the confusion matrix.
# Import confusion matrix
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [93]:
# Generate the confusion matrix and classification report
print ("THIS IS THE CONFUSION MATRIX:")
print(confusion_matrix(label_test, bird_bone_pred))
print ("THIS IS THE CLASSIFICATION REPORT:")
print(classification_report(label_test, bird_bone_pred))

THIS IS THE CONFUSION MATRIX:
[[ 6  0  4  0  0  0]
 [ 3  9  0  0  0  0]
 [ 4  0 27  0  0  0]
 [ 0  0  0 25  0  4]
 [ 0  0  0  0  3  3]
 [ 0  0  3  3  0 10]]
THIS IS THE CLASSIFICATION REPORT:
              precision    recall  f1-score   support

           P       0.46      0.60      0.52        10
           R       1.00      0.75      0.86        12
          SO       0.79      0.87      0.83        31
          SW       0.89      0.86      0.88        29
           T       1.00      0.50      0.67         6
           W       0.59      0.62      0.61        16

    accuracy                           0.77       104
   macro avg       0.79      0.70      0.73       104
weighted avg       0.79      0.77      0.77       104

